import './globals.css'
import { Inter, JetBrains_Mono } from 'next/font/google'


const jetbrainsmono = JetBrains_Mono({ subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jetbrainsmono.className}>{children}</body>
    </html>
  )
}
